Locales['es'] = {
  -- Cloakroom
  ['cloakroom'] = 'Guardarropa',
  ['ems_clothes_civil'] = 'Camiseta',
  ['ems_clothes_ems'] = 'Equipo de ambulancia',
  -- Vehicles
  ['ambulance'] = 'ambulancia',
  ['helicopter_prompt'] = 'presiona ~INPUT_CONTEXT~ para acceder ~y~Acciones helicopteros~s~.',
  ['garage_prompt'] = 'presiona ~INPUT_CONTEXT~ to access the ~y~Vehicle Actions~s~.',
  ['garage_title'] = 'acciones vehiculares',
  ['garage_stored'] = 'almacenado',
  ['garage_notstored'] = 'no en el garage',
  ['garage_storing'] = 'estamos intentando remover el coche, que no haya nadie cerca!.',
  ['garage_has_stored'] = 'el vehiculo se guardo en tu garage',
  ['garage_has_notstored'] = 'no tienes vehiculos cerca',
  ['garage_notavailable'] = 'tu vehiculo no esta guardado en el garage.',
  ['garage_blocked'] = 'no tienes puntos de spawn!',
  ['garage_empty'] = 'no tienes vehiculos en el garage.',
  ['garage_released'] = 'sacaste tu vehiculo del garage.',
  ['garage_store_nearby'] = 'no hay vehiculos cerca.',
  ['garage_storeditem'] = 'abrir garage',
  ['garage_storeitem'] = 'guardar vehiculo',
  ['garage_buyitem'] = 'tienda de vehiculos',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'tienda de vehiculos',
  ['vehicleshop_confirm'] = 'dquieres comprar este vehiculo?',
  ['vehicleshop_bought'] = 'has comprado ~y~%s~s~ for ~g~$%s~s~',
  ['vehicleshop_money'] = 'no puedes permitirte ese vehiculo',
  ['vehicleshop_awaiting_model'] = 'el vehiculo esta ~g~CARGANDO & DESCARGABDOSE~s~ porfavor espera',
  ['confirm_no'] = 'no',
  ['confirm_yes'] = 'si',
  -- Action Menu
  ['revive_inprogress'] = 'reanimación en curso',
  ['revive_complete'] = 'has sido reanimado ~y~%s~s~',
  ['revive_complete_award'] = 'has sido reanimado ~y~%s~s~, ~g~$%s~s~',
  ['revive_fail_offline'] = 'ese jugador no esta en linea',
  ['heal_inprogress'] = 'estas curando!',
  ['heal_complete'] = 'has curado a ~y~%s~s~',
  ['no_players'] = 'ningún jugador cerca',
  ['player_not_unconscious'] = 'n\'estás inconsciente',
  ['player_not_conscious'] = 'ese jugador no esta inconciente!',
  -- Boss Menu
  ['boss_actions'] = 'boss Actions',
  -- Misc
  ['invalid_amount'] = '~r~cantidad no válida',
  ['actions_prompt'] = 'presiona ~INPUT_CONTEXT~ acceder a ~y~Ambulance Actions~s~.',
  ['deposit_amount'] = 'cantidad de fianza depositada',
  ['money_withdraw'] = 'cantidad de fianza retirada',
  ['fast_travel'] = 'presiona ~INPUT_CONTEXT~ para viajar rapdio.',
  ['open_pharmacy'] = 'presiona ~INPUT_CONTEXT~ para abrir la farmacia.',
  ['pharmacy_menu_title'] = 'farmacia',
  ['pharmacy_take'] = 'tomar <span style="color:blue;">%s</span>',
  ['medikit'] = 'medikit',
  ['bandage'] = 'venda',
  ['max_item'] = 'estas cargando muchos.',
  -- F6 Menu
  ['ems_menu'] = 'ayuda ciudadana',
  ['ems_menu_title'] = 'ambulancia - Ayuda Ciudadana',
  ['ems_menu_revive'] = 'reanimar',
  ['ems_menu_putincar'] = 'meter en el vehículo',
  ['ems_menu_small'] = 'curar heridas comunes',
  ['ems_menu_big'] = 'curar heridas mayores',
  -- Phone
  ['alert_ambulance'] = 'alerta de ambulancia',
  -- Death
  ['respawn_available_in'] = 'respawn available in ~b~%s minutes %s seconds~s~',
  ['respawn_bleedout_in'] = 'you will bleed out in ~b~%s minutes %s seconds~s~\n',
  ['respawn_bleedout_prompt'] = 'hold [~b~E~s~] to respawn',
  ['respawn_bleedout_fine'] = 'hold [~b~E~s~] to respawn for ~g~$%s~s~',
  ['respawn_bleedout_fine_msg'] = 'you paid ~r~$%s~s~ to respawn.',
  ['distress_send'] = 'presiona [~b~G~s~] para enviar la alerta',
  ['distress_sent'] = 'se envio la alerta a las autoridades!',
  ['combatlog_message'] = 'fuiste forzado a spawnear debido a un problema anterior.',
  -- Revive
  ['revive_help'] = 'reviver un jugador',
  -- Item
  ['used_medikit'] = 'usaste un ~y~1x~s~ medikit',
  ['used_bandage'] = 'usase un ~y~1x~s~ bandage',
  ['not_enough_medikit'] = 'no tienes ~b~medikit~s~.',
  ['not_enough_bandage'] = 'no tienes ~b~bandage~s~.',
  ['healed'] = 'fuiste tratado.',
  -- Blips
  ['blip_hospital'] = 'hospital',
  ['blip_dead'] = 'jugador inconciente',
}
